# Generated by Django 5.2 on 2025-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('age', models.IntegerField(max_length=3, null=True)),
                ('date', models.DateTimeField(max_length=300, null=True)),
            ],
        ),
    ]
